{{- $epsagonToken := include "cluster-agent.epsagonToken" . -}}
{{- if $epsagonToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cluster-agent.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "cluster-agent.labels" . | indent 4 }}
type: Opaque
data:
  epsagonToken: {{ $epsagonToken | b64enc }}
{{- end }}